### ISSUE TITLE
Autofix valid dagster meta configuration for asset_key

### ISSUE THREAD

**Issue by justin-fundrise** [dbt-labs/dbt-autofix#44]
I am running into an issue where dbt-autofix is correcting this format: 

```
sources:
  - name: jaffle_shop
    tables:
      - name: orders
        meta:
          dagster:
            asset_key: ['snowflake', 'jaffle_shop', 'orders']
```

and changing it to be this format: 
```
sources:
  - name: jaffle_shop
    tables:
      - name: orders
         config:
             meta:
               dagster:
                  asset_key: ['snowflake', 'jaffle_shop', 'orders']
```

in the dagster documentation it appears to be legitimate yaml structure, is this something that dbt-autofix can accept as valid? 

https://docs.dagster.io/integrations/libraries/dbt/reference#customizing-asset-keys

This is also giving a warning in the new VS Code DBT extension dbt-fusion when trying to "Preview File" . 

```
warning: (soon: error) dbt1060: Ignored unexpected key `"meta"`. YAML path: `meta`.
```
