### ISSUE TITLE
Support Multiline values containing colons

### ISSUE THREAD

**Issue by jaypeedevlin** [dbt-labs/dbt-autofix#45]
We have YAML equivalent to this:

```yml
version: 2
models:
  - name: foo
    description: |-
      This is a model about something
      
      This model contains:
        * This
        * That
```

This fails with:

```
ScannerError: mapping values are not allowed here
  in "<unicode string>", line 37, column 36:
          This model contains:
```
